apiVersion: v1
kind: ConfigMap
metadata:
  name: tenants-init-sql
  namespace: local
data:
  create-tenants-db.sql: |
    SELECT 'CREATE DATABASE tenants'
    WHERE NOT EXISTS (SELECT
                      FROM pg_database
                      WHERE datname = 'tenants')
    \gexec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants-api
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenants-api
  template:
    metadata:
      labels:
        app: tenants-api
    spec:
      volumes:
        - name: init-sql
          configMap:
            name: tenants-init-sql
      initContainers:
        - name: init-db
          image: postgres:16
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until pg_isready -h $(DATABASE_HOST) -U $(DATABASE_USERNAME); do
                sleep 2;
              done;
              echo "Running DB init script...";
              export PGPASSWORD=$DATABASE_PASSWORD;
              psql -h $(DATABASE_HOST) -U $(DATABASE_USERNAME) -f /sql/create-tenants-db.sql postgres
          envFrom:
            - configMapRef:
                name: tenants-api-config
            - secretRef:
                name: tenants-api-secrets
          volumeMounts:
            - name: init-sql
              mountPath: /sql

      containers:
        - name: tenants-api
          image: docker.io/cgayet/tenants-api:0.0.1
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: tenants-api-config
            - secretRef:
                name: tenants-api-secrets