apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tenants-api-route
  namespace: local
spec:
  parentRefs:
    - name: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tenants-api
          port: 80
